---
credentials:
  type: object
  description: "Mapping of name to an object containing credential information"
  properties:
    server:
      type: string
      description: "Hostname/IP of the PRTG server"
    transport:
      type: string
      description: "HTTP or HTTPS transport to use when communicating with the API"
      default: "https"
    verify_ssl:
      type: boolean
      description: "Should the server SSL certificates be verified?"
      default: true
    username:
      type: string
      description: "User to authenticate as,"
    password:
      type: string
      description: "Password to authenticate with."
      secret: true
